# Generated by Django 4.1.7 on 2023-04-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='catagory',
            field=models.CharField(default='patient', max_length=100),
        ),
    ]
