# Generated by Django 4.1.7 on 2023-04-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_options_alter_doctor_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='catagory',
            field=models.CharField(default='doctor', max_length=100),
        ),
    ]
